import {
  badgeComponent,
  escapeMarkdownCell,
  escapeMarkdownLabel,
  escapeXml,
} from "../core/escape.js";
import type { ProfileConfig } from "../core/types.js";

function picture(baseName: string, alt: string): string {
  return `<picture>\n  <source media="(prefers-color-scheme: dark)" srcset="assets/${baseName}-dark.svg">\n  <source media="(prefers-color-scheme: light)" srcset="assets/${baseName}-light.svg">\n  <img alt="${escapeXml(alt)}" src="assets/${baseName}-light.svg" width="100%">\n</picture>`;
}

function renderBadges(config: ProfileConfig): string {
  if (!config.settings.show_badges) return "";
  const username = badgeComponent(config.github.username);
  const badges = [
    `![profile](https://img.shields.io/badge/profile-${username}-${config.theme.primary.slice(1)}?style=flat-square&labelColor=102934)`,
    `![layers](https://img.shields.io/badge/layers-${config.layers.length}-${config.theme.secondary.slice(1)}?style=flat-square&labelColor=102934)`,
  ];
  return `${badges.join(" ")}\n\n`;
}

function renderFlagships(config: ProfileConfig): string {
  const rows = config.flagships.map((project) => {
    const repo = escapeMarkdownLabel(project.repo);
    const description = escapeMarkdownCell(project.description) || "—";
    const stars = config.settings.show_stars
      ? ` ![stars](https://img.shields.io/github/stars/${badgeComponent(config.github.username)}/${badgeComponent(project.repo)}?style=flat-square&label=%E2%98%85)`
      : "";
    return `| [\`${repo}\`](https://github.com/${config.github.username}/${project.repo})${stars} | ${escapeMarkdownCell(project.role)} | ${description} |`;
  });
  return `## Flagship systems\n\n| Repository | Role | Purpose |\n| --- | --- | --- |\n${rows.join("\n")}`;
}

function renderModules(config: ProfileConfig): string {
  if (config.module_groups.length === 0) return "";
  return config.module_groups
    .map((group) => {
      const rows = group.projects
        .map(
          (project) =>
            `| [\`${escapeMarkdownLabel(project.repo)}\`](https://github.com/${config.github.username}/${project.repo}) | ${escapeMarkdownCell(project.description) || "—"} |`,
        )
        .join("\n");
      return `<details>\n<summary><strong>${escapeXml(group.name)}</strong> · ${group.projects.length} modules</summary>\n\n| Module | Purpose |\n| --- | --- |\n${rows}\n\n</details>`;
    })
    .join("\n\n");
}

function renderLinks(config: ProfileConfig): string {
  if (!config.links || config.links.length === 0) return "";
  const links = config.links
    .map(
      (link) => `<a href="${escapeXml(link.url)}">${escapeXml(link.label)}</a>`,
    )
    .join(" · ");
  return `<p align="center">${links}</p>`;
}

export function renderReadme(config: ProfileConfig): string {
  return `${picture("hero", `${config.identity.name} profile control plane`)}\n\n${renderBadges(config)}${config.identity.tagline ? `${escapeMarkdownCell(config.identity.tagline)}\n\n` : ""}${renderFlagships(config)}\n\n## Closed-loop architecture\n\n${picture("closed-loop", `${config.identity.name} architecture map`)}\n\n## Module registry\n\n${renderModules(config) || "No modules declared."}\n\n${renderLinks(config)}\n\n<!-- Generated by profile-control-plane. Edit profile.yaml, not this file. -->\n`;
}
